replicaCount: 3
curity:
  config:
    license: true
    cluster:
      enabled: true
    uiEnabled: true
    configuration: 
      - secretRef:
          name: curity-config-secret
          items:
            - key: configuration.xml
              path: configuration.xml
    environmentVariableSecrets:
     - name: "PASSWORD"
       secretName: "curity-cluster-secret"
       secretKey: "password"
     - curity-vars
  admin:
    service:
      type: ClusterIP
  runtime:
    service:
      type: ClusterIP
      port: 8443
ingress:
  enabled: false
  admin:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
      kubernetes.io/ingress.class: "nginx"
    host: dev.curity-admin.local
    paths:
      - /
  runtime:
    extraEnv:
      - name: "ADMIN_SERVICE_NAME"
        value: "curity-dev-idsvr-admin-svc"
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: role
                  operator: In
                  values:
                    - curity-runtime
            topologyKey: "kubernetes.io/hostname"
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      kubernetes.io/ingress.class: "nginx"
    host: dev.curity.local
    paths:
      - /