curity:
  config:
    license: true
    password:
      secretName: curity-admin-password
      key: password
    uiEnabled: true
  admin:
    service:
      type: ClusterIP
      port: 6749
  runtime:
    service:
      type: ClusterIP
      port: 8443
ingress:
  runtime:
    enabled: false 
  admin:
    enabled: false