curity:
  adminUIHttp: true
  adminUIPort: 6749
  config:
    license: true
    password: "Dummy"
    uiEnabled: true
    environmentVariableSecrets:
      - curity-admin-password
    configuration: 
      - secretRef:
          name: curity-config-secret
          items:
            - key: configuration.xml
              path: configuration.xml
  admin:
    service:
      type: ClusterIP
  runtime:
    service:
      type: ClusterIP
      port: 8443
ingress:
  admin:
    enabled: true
    ingressClassName: nginx
    host: curity-admin.local
    paths:
      - /
    pathType: ImplementationSpecific
    
  runtime:
    enabled: true
    ingressClassName: nginx
    host: curity.local
    paths:
      - /
    pathType: ImplementationSpecific