curity:
  adminUIHttp: true
  adminUIPort: 6749
  config:
    license: true
    password: "Dummy"
    uiEnabled: true
    environmentVariableSecrets:
      - curity-admin-password
  admin:
    service:
      type: ClusterIP
  runtime:
    service:
      type: ClusterIP
      port: 8443
ingress:
  runtime:
    enabled: false 
  admin:
    enabled: false