curity:
  adminUiHttp: true
  config:
    license: true
    password: "Dummy"
    uiEnabled: true
    environmentVariableSecrets:
      - curity-admin-password
    configuration: 
      - secretRef:
          name: curity-config-secret
          items:
            - key: configuration.xml
              path: configuration.xml
  admin:
    service:
      type: ClusterIP
  runtime:
    service:
      type: ClusterIP
      port: 8443
ingress:
  enabled: false
  admin:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
      kubernetes.io/ingress.class: "nginx"
    host: curity-admin.local
    paths:
      - /
  runtime:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
      kubernetes.io/ingress.class: "nginx"
    host: curity.local
    paths:
      - /