curity:
  config:
    uiEnabled: true
    configuration: 
      - secretRef:
          name: curity-config-secret
          items:
            - key: configuration.xml
              path: configuration.xml
    environmentVariableSecrets:
     - curity-vars
  admin:
    service:
      type: ClusterIP
  runtime:
    service:
      type: ClusterIP
      port: 8443
ingress:
  enabled: false
  admin:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
      kubernetes.io/ingress.class: "nginx"
    host: dev.curity-admin.local
    paths:
      - /
    tls:
      - hosts:
          - dev.curity-admin.local
        secretName: curity-admin-tls-secret
  runtime:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      kubernetes.io/ingress.class: "nginx"
    host: dev.curity.local
    paths:
      - /
    tls:
      - hosts:
          - dev.curity.local
        secretName: curity-runtime-tls-secret